### ISSUE TITLE
Read SIMPLE source code from Text File

### ISSUE THREAD

**Issue by blaqkrow** [G12ProjectTeam/SpaProjectRepo#2]
read source code from text file

**Comment by danielweide** [comment]
#1 it appears that I cannot proceed without issue #1 because that function includes a parser, which may cause merge conflict if worked on by 2 person

**Comment by danielweide** [comment]
@blaqkrow It appears that my issue does not exist as the idea is just to load the file onto the text field which was already fulfilled at the project originally. So do we close this issue? As I dont think there is area to fix since it's purpose is just to load the text to the textfield

**Comment by danielweide** [comment]
No need for this function So I will be closing it
